pip install os
pip install requests
pip install tls_client
pip install datetime
pip install sys
pip install hashlib
pip install threading
pip install websocket
pip install websocket_client
pip install json
pip install time
pip install httpx
pip install typing
pip install subprocess
pip install colorama
pip install emoji
pip install fade